---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "mimir"
  namespace: "abuse-api-dev"
  labels:
    app: "mimir"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "mimir"
  template:
    metadata:
      labels:
        app: "mimir"
    spec:
      imagePullSecrets:
        -
          name: "dcu-artifactory-creds"
      containers:
        -
          name: "mimir"
          imagePullPolicy: "Always"
          image: "docker-dcu-local.artifactory.secureserver.net/mimir:dev"
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
          env:
          - name: BUILD_DATE
            value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          - name: sysenv
            value: dev
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-phishstory-v2
                key: password
          - name: REDIS
            value: mimir-redis.abuse-api-dev.svc.cluster.local