---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mimir
  namespace: abuse-api-ote
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - mimir.cset.int.ote-gdcorp.tools
      secretName: cset-wildcard
  rules:
  - host: mimir.cset.int.ote-gdcorp.tools
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mimir
            port:
              number: 5000
